"""
content_bank.py
───────────────
50 pre-written listening clips — static content, no LLM generation.
Audio is synthesised once via Azure TTS and served per session.

Layout:
  REPEAT_CLIPS (50) — candidate repeats the sentence verbatim
  QNA_CLIPS    (50) — candidate answers 2 questions about the passage

Per session: 2 REPEAT + 2 QnA selected randomly → different every time.

Each clip carries key_facts used by the accuracy scorer as a ground-truth
signal (keyword matching), making scoring more deterministic and faster.
"""

import random
from copy import deepcopy
from dataclasses import dataclass, field


@dataclass
class ListeningClip:
    clip_id:        str
    task_type:      str            # "REPEAT" or "QnA"
    reference_text: str
    questions:      list = field(default_factory=list)   # QnA only — 2 questions
    key_facts:      list = field(default_factory=list)
    # For REPEAT: flat list of must-appear keywords
    # For QnA:   list of lists — key_facts[0] for Q1, key_facts[1] for Q2


# ─────────────────────────────────────────────────────────────────────────────
# REPEAT CLIPS
# ─────────────────────────────────────────────────────────────────────────────

REPEAT_CLIPS: list[ListeningClip] = [
    ListeningClip("r01","REPEAT","My neighbour knocked on my door this morning to let me know that a parcel had been delivered to her house by mistake, so I went over and picked it up before leaving for work.",key_facts=["neighbour","parcel","delivered","mistake","work"]),
    ListeningClip("r02","REPEAT","The electricity bill for last month was much higher than usual, so we checked every room and found that the air conditioner in the guest room had been left running for three days.",key_facts=["electricity","higher","air conditioner","guest room","three days"]),
    ListeningClip("r03","REPEAT","I missed my usual train this morning because the alarm on my phone did not go off, and by the time I reached the station, the doors had already closed.",key_facts=["train","alarm","phone","station","closed"]),
    ListeningClip("r04","REPEAT","The restaurant at the corner of the street has changed its menu and now serves a wider variety of South Indian breakfast options from six in the morning.",key_facts=["restaurant","corner","menu","South Indian","six"]),
    ListeningClip("r05","REPEAT","Please ensure that you carry both your hall ticket and a government-issued photo identification card to the examination centre, as entry will not be permitted without them.",key_facts=["hall ticket","photo identification","examination centre","entry","permitted"]),
    ListeningClip("r06","REPEAT","The old banyan tree near the school gate was cut down last week after the municipal corporation declared it unsafe, and a sapling will be planted in its place next month.",key_facts=["banyan tree","school","municipal","unsafe","sapling"]),
    ListeningClip("r07","REPEAT","Passengers travelling by the Shatabdi Express on Sunday are advised that the train will depart from platform seven instead of platform three due to maintenance work on the tracks.",key_facts=["Shatabdi","Sunday","platform seven","platform three","maintenance"]),
    ListeningClip("r08","REPEAT","The water supply to the apartments in Block C will be interrupted between ten in the morning and two in the afternoon on Thursday for pipe-cleaning work.",key_facts=["water supply","Block C","ten","two","Thursday"]),
    ListeningClip("r09","REPEAT","My sister recently passed her driving test on the third attempt and immediately bought a second-hand hatchback that she had been saving up for since last year.",key_facts=["driving test","third","second-hand","hatchback","saving"]),
    ListeningClip("r10","REPEAT","The college has announced that the semester exams originally scheduled for March have been postponed to the second week of April due to construction work on the new examination block.",key_facts=["semester","March","postponed","April","construction"]),
    ListeningClip("r11","REPEAT","The pharmacy near the bus stop closes at nine in the evening on weekdays and at six on Sundays, so it is best to collect your medicines before the weekend.",key_facts=["pharmacy","nine","weekdays","six","Sunday"]),
    ListeningClip("r12","REPEAT","The yoga class that meets in the community hall every Tuesday and Thursday morning has now increased its batch size from fifteen to twenty-five participants.",key_facts=["yoga","Tuesday","Thursday","fifteen","twenty-five"]),
    ListeningClip("r13","REPEAT","Our flight was delayed by almost two hours because of heavy fog at the departure airport, but we were given food vouchers worth two hundred rupees each while we waited.",key_facts=["flight","two hours","fog","food vouchers","two hundred"]),
    ListeningClip("r14","REPEAT","The building management has requested all residents to hand over a duplicate set of keys to the security desk by Saturday evening in case of emergency access.",key_facts=["duplicate","keys","security desk","Saturday","emergency"]),
    ListeningClip("r15","REPEAT","The public swimming pool near the stadium is open from five thirty in the morning until eight at night, except on Mondays when it is closed for cleaning.",key_facts=["swimming pool","five thirty","eight","Mondays","cleaning"]),
    ListeningClip("r16","REPEAT","Our neighbour's daughter has been selected for the state-level science olympiad and will travel to Bhopal next week to represent the district along with two other students from her school.",key_facts=["science olympiad","Bhopal","next week","district","two"]),
    ListeningClip("r17","REPEAT","The new supermarket that opened last month on the main road offers a free home delivery service for all purchases above five hundred rupees within a five-kilometre radius.",key_facts=["supermarket","home delivery","five hundred","five kilometre","radius"]),
    ListeningClip("r18","REPEAT","Please be informed that the company's annual general meeting will be held on the twenty-third of this month in Conference Room A on the fourth floor, starting at ten o'clock sharp.",key_facts=["annual general meeting","twenty-third","Conference Room A","fourth floor","ten"]),
    ListeningClip("r19","REPEAT","The doctor advised my father to walk at least thirty minutes every morning and to avoid fried food entirely, as his cholesterol levels have gone up compared to the last check-up.",key_facts=["doctor","thirty minutes","fried food","cholesterol","check-up"]),
    ListeningClip("r20","REPEAT","A second-hand book fair is being organised at the city park this Saturday and Sunday between nine in the morning and seven in the evening, with books starting from as low as twenty rupees.",key_facts=["book fair","Saturday","Sunday","nine","seven","twenty"]),
    ListeningClip("r21","REPEAT","The RTO office on the service road will be closed on Wednesday and Thursday this week due to a statewide government training programme for staff members.",key_facts=["RTO","Wednesday","Thursday","government","training"]),
    ListeningClip("r22","REPEAT","Several residents in our apartment complex have started a weekend carpooling arrangement to reduce fuel expenses and the number of vehicles going in and out of the parking area.",key_facts=["residents","weekend","carpooling","fuel","parking"]),
    ListeningClip("r23","REPEAT","The local municipality will be spraying mosquito repellent across the ward this evening, so residents are requested to keep their windows closed between seven and nine.",key_facts=["municipality","mosquito","repellent","windows","seven","nine"]),
    ListeningClip("r24","REPEAT","My grandmother has recently taken up painting as a hobby and attends a weekend workshop every Saturday morning at a small studio about two kilometres from our house.",key_facts=["grandmother","painting","workshop","Saturday","two kilometres"]),
    ListeningClip("r25","REPEAT","The HR team is conducting a skills mapping survey for all departments this week, and every employee is expected to fill in the form by end of day Wednesday.",key_facts=["HR","skills mapping","departments","Wednesday","form"]),
    ListeningClip("r26","REPEAT","The highway between the city and the industrial zone is being widened from four lanes to six lanes, and the project is expected to be completed by December.",key_facts=["highway","four lanes","six lanes","widened","December"]),
    ListeningClip("r27","REPEAT","I realised only at the billing counter that I had forgotten my wallet at home, so my colleague kindly paid for my lunch and I transferred the amount to him in the evening.",key_facts=["wallet","home","colleague","lunch","transferred"]),
    ListeningClip("r28","REPEAT","The coaching centre has shifted its evening batch timing from five o'clock to five thirty because several students were arriving late due to school dismissal delays.",key_facts=["coaching","evening","five","five thirty","students"]),
    ListeningClip("r29","REPEAT","A stray dog that had been living outside our office gate for nearly two years was recently adopted by one of our security guards and taken to his home in Ambattur.",key_facts=["stray dog","two years","adopted","security guard","Ambattur"]),
    ListeningClip("r30","REPEAT","All visitors entering the hospital premises are required to show a valid ID proof at the reception and collect a visitor pass before proceeding to any ward.",key_facts=["hospital","ID proof","reception","visitor pass","ward"]),
    ListeningClip("r31","REPEAT","The overnight bus to Madurai has been rescheduled from eleven fifteen to eleven forty-five following a request from a drivers' union due to road safety concerns.",key_facts=["Madurai","eleven fifteen","eleven forty-five","union","road safety"]),
    ListeningClip("r32","REPEAT","The apartment association has decided to replace all the lights in the common areas with LED fittings to reduce the monthly electricity bill by at least forty percent.",key_facts=["apartment","LED","common areas","electricity","forty percent"]),
    ListeningClip("r33","REPEAT","My uncle who lives in Canada is visiting us for three weeks starting from the fifteenth of next month, and the whole family is planning a short trip to Ooty during his stay.",key_facts=["Canada","three weeks","fifteenth","Ooty","family"]),
    ListeningClip("r34","REPEAT","The police have issued a traffic advisory for the city centre this weekend due to a cultural procession, and motorists are advised to take the ring road to avoid delays.",key_facts=["police","traffic advisory","weekend","procession","ring road"]),
    ListeningClip("r35","REPEAT","The school principal has announced that the annual sports day has been moved from the last Friday of this month to the second Saturday of next month.",key_facts=["principal","sports day","Friday","second Saturday","next month"]),
    ListeningClip("r36","REPEAT","Due to an unexpected system upgrade, access to the employee self-service portal will be unavailable from midnight tonight until six o'clock tomorrow morning.",key_facts=["system upgrade","self-service portal","midnight","six","tomorrow"]),
    ListeningClip("r37","REPEAT","The landlord informed us that the painting work on the exterior of the building will begin on Monday and is expected to take around ten days to finish.",key_facts=["landlord","painting","exterior","Monday","ten days"]),
    ListeningClip("r38","REPEAT","I recently joined a reading club that meets every other Sunday at a cafe near the library, where members take turns presenting books they have read over the past fortnight.",key_facts=["reading club","Sunday","cafe","library","fortnight"]),
    ListeningClip("r39","REPEAT","The municipal school near the railway colony has received a government grant of fifteen lakh rupees to build a new computer lab and upgrade its science equipment.",key_facts=["municipal school","government grant","fifteen lakh","computer lab","science"]),
    ListeningClip("r40","REPEAT","The vegetable vendor who usually comes to our street on Tuesday and Friday mornings will not be coming this week as he has gone to his hometown for a family function.",key_facts=["vegetable vendor","Tuesday","Friday","hometown","family function"]),
    ListeningClip("r41","REPEAT","The IT helpdesk has reminded all staff to change their system passwords before the end of this month as part of the company's quarterly security compliance process.",key_facts=["IT helpdesk","passwords","end of this month","quarterly","security"]),
    ListeningClip("r42","REPEAT","A popular local singer performed for over two hours at the open-air auditorium last Saturday evening, drawing a crowd of nearly three thousand people from across the city.",key_facts=["singer","two hours","auditorium","Saturday","three thousand"]),
    ListeningClip("r43","REPEAT","The post office on Gandhi Road will have extended working hours from eight in the morning until seven in the evening starting this Monday, to handle the increased volume of festive-season parcels.",key_facts=["post office","Gandhi Road","eight","seven","Monday"]),
    ListeningClip("r44","REPEAT","My colleague has been transferred to the Coimbatore branch and will be leaving on the twentieth of this month, so the team has planned a small farewell lunch for her this Friday.",key_facts=["transferred","Coimbatore","twentieth","farewell","Friday"]),
    ListeningClip("r45","REPEAT","The corporation has decided to introduce a new garbage collection system in which wet waste and dry waste must be kept in separate bins and put out on alternate days.",key_facts=["garbage","wet waste","dry waste","separate bins","alternate days"]),
    ListeningClip("r46","REPEAT","The blood donation camp organised by the Rotary Club will be held at the community centre on the eighth of this month from eight in the morning until one in the afternoon.",key_facts=["blood donation","Rotary Club","eighth","eight","one"]),
    ListeningClip("r47","REPEAT","The bridge over the river has been closed to heavy vehicles until further notice following an inspection that revealed minor cracks in the foundation last week.",key_facts=["bridge","heavy vehicles","closed","inspection","cracks"]),
    ListeningClip("r48","REPEAT","The principal has instructed that all students must submit their project reports in printed format by the last working day of the month and not send them by email.",key_facts=["principal","project reports","printed","last working day","email"]),
    ListeningClip("r49","REPEAT","There is a free legal aid clinic held every first and third Saturday at the district court premises, where lawyers volunteer to help citizens with document-related questions.",key_facts=["legal aid","first","third Saturday","district court","lawyers"]),
    ListeningClip("r50","REPEAT","The office cafeteria will introduce a loyalty card scheme from next week where every tenth meal is free, and cards can be collected from the cashier during breakfast hours.",key_facts=["cafeteria","loyalty card","tenth","free","cashier"]),
]


# ─────────────────────────────────────────────────────────────────────────────
# QnA CLIPS
# ─────────────────────────────────────────────────────────────────────────────

QNA_CLIPS: list[ListeningClip] = [
    ListeningClip("q01","QnA","Karthik has been commuting to work by bicycle for the past six months to save money and stay fit. He covers a distance of twelve kilometres each way and usually reaches the office by eight forty-five in the morning.",questions=["How long has Karthik been commuting by bicycle?","What distance does he cover one way?"],key_facts=[["six months"],["twelve","12"]]),
    ListeningClip("q02","QnA","The local government has announced the construction of a new sports complex near the river, which will include a swimming pool, a badminton court, and a running track. The project is expected to be completed within eighteen months.",questions=["What facilities will the new sports complex include?","How long will the construction take?"],key_facts=[["swimming pool","badminton","running track"],["eighteen months","18"]]),
    ListeningClip("q03","QnA","Meera quit her corporate job two years ago to start a home bakery. She now takes custom orders for cakes and snacks and delivers within a ten-kilometre radius. Her busiest days are Fridays and Saturdays.",questions=["Why did Meera quit her corporate job?","On which days is she busiest?"],key_facts=[["home bakery","start a bakery"],["Friday","Saturday"]]),
    ListeningClip("q04","QnA","The school canteen has stopped selling packaged chips and fizzy drinks as part of a new health initiative. Students can now choose from fresh juices, salads, and homemade snacks. The change came into effect from the beginning of this term.",questions=["What has the school canteen stopped selling?","When did the new policy come into effect?"],key_facts=[["chips","fizzy drinks"],["beginning of this term","this term"]]),
    ListeningClip("q05","QnA","A fire broke out in a textile warehouse on the outskirts of the city early on Wednesday morning. Three fire engines were dispatched and the blaze was brought under control within two hours. No casualties were reported.",questions=["Where did the fire break out?","How long did it take to bring the fire under control?"],key_facts=[["textile warehouse","outskirts"],["two hours"]]),
    ListeningClip("q06","QnA","The city metro authority has extended the blue line by four stations towards the southern suburbs. The extension will be inaugurated on the twenty-sixth and will be free for commuters during the first three days.",questions=["How many new stations have been added to the blue line?","For how many days will the service be free?"],key_facts=[["four stations","four"],["three days","three"]]),
    ListeningClip("q07","QnA","Preethi has recently started volunteering at an animal shelter every Sunday morning. She helps bathe the animals, prepare their food, and assist in finding adoptive families. She has already helped three dogs get adopted.",questions=["When does Preethi volunteer at the animal shelter?","How many dogs has she helped get adopted?"],key_facts=[["Sunday"],["three"]]),
    ListeningClip("q08","QnA","The district collector's office has launched a new grievance portal where citizens can file complaints related to roads, water, and waste management. All complaints will be acknowledged within twenty-four hours and resolved within fifteen working days.",questions=["What types of complaints can citizens file on the portal?","Within how many days will complaints be resolved?"],key_facts=[["roads","water","waste"],["fifteen","15"]]),
    ListeningClip("q09","QnA","Ramesh moved to Singapore three months ago for a project with his company. He works in the technology division and manages a team of eight people. He plans to return to India by December.",questions=["Where is Ramesh working currently?","How many people does he manage?"],key_facts=[["Singapore"],["eight","8"]]),
    ListeningClip("q10","QnA","The heritage walk organised by the city tourism department takes visitors through twelve historic landmarks in the old city. The walk starts at six in the morning, lasts about three hours, and is available every weekend.",questions=["How many landmarks does the heritage walk cover?","At what time does the walk start?"],key_facts=[["twelve","12"],["six","6 AM"]]),
    ListeningClip("q11","QnA","A group of college students from the engineering department has built a solar-powered water purifier and donated it to a village school in the district. The purifier can clean up to two hundred litres of water per day.",questions=["Who built the solar-powered water purifier?","How much water can it clean per day?"],key_facts=[["engineering students","college students"],["two hundred litres","200"]]),
    ListeningClip("q12","QnA","The apartment complex has decided to install CCTV cameras on all four floors and at the main entrance following a series of minor thefts last month. The installation will be completed by the end of next week.",questions=["Why has the apartment complex decided to install CCTV cameras?","When will the installation be completed?"],key_facts=[["thefts","theft"],["end of next week"]]),
    ListeningClip("q13","QnA","Sunita has been selected as the head of the newly formed environmental committee at her workplace. The committee will meet on the first Monday of every month and will focus on reducing plastic usage within the office.",questions=["What is the focus of the environmental committee?","When does the committee meet?"],key_facts=[["plastic","reducing plastic"],["first Monday","every month"]]),
    ListeningClip("q14","QnA","The government hospital in the town has introduced a token-based appointment system to reduce waiting times. Patients can now book their slots online or by calling the helpline number. Walk-in appointments are still available for emergency cases.",questions=["How can patients book appointments?","Are walk-in appointments still available?"],key_facts=[["online","helpline","calling"],["yes","emergency","walk-in"]]),
    ListeningClip("q15","QnA","The popular street food market near the beach road operates only on Thursday and Friday evenings from five to ten. It has over forty stalls offering snacks from different regions of the country and attracts a large crowd each week.",questions=["On which days does the street food market operate?","How many stalls are there at the market?"],key_facts=[["Thursday","Friday"],["forty","40"]]),
    ListeningClip("q16","QnA","A retired school teacher named Mr. Annadurai runs free evening classes for children from low-income families in his neighbourhood. He teaches mathematics and English to around thirty students aged between eight and fourteen.",questions=["Who runs the free evening classes?","How many students attend the classes?"],key_facts=[["Annadurai","Mr. Annadurai"],["thirty","30"]]),
    ListeningClip("q17","QnA","The city's largest mall will undergo renovation from the first of February for a period of two months. During this time, the food court and cinema will remain open, but the retail floors on levels three and four will be closed.",questions=["How long will the mall renovation last?","Which areas will remain open during renovation?"],key_facts=[["two months"],["food court","cinema"]]),
    ListeningClip("q18","QnA","Divya has been practising classical dance since the age of seven and recently gave her first solo stage performance in front of an audience of over five hundred people. Her teacher says she is ready for national-level competitions.",questions=["Since what age has Divya been practising classical dance?","How large was the audience at her solo performance?"],key_facts=[["seven","age of seven"],["five hundred","500"]]),
    ListeningClip("q19","QnA","The local cooperative bank is offering a special fixed deposit scheme this month with an interest rate of eight point five percent per year for deposits made for a minimum of two years. Senior citizens will receive an additional half percent.",questions=["What is the interest rate offered in the special scheme?","What extra benefit do senior citizens receive?"],key_facts=[["eight point five","8.5"],["half percent","0.5 percent"]]),
    ListeningClip("q20","QnA","The railway station is being upgraded with new waiting areas, digital display boards, and a dedicated area for differently-abled passengers. The work is funded by the central government at a cost of four crore rupees.",questions=["What new features are being added to the railway station?","How much does the upgrade cost?"],key_facts=[["waiting areas","digital boards","differently-abled"],["four crore","4 crore"]]),
    ListeningClip("q21","QnA","My friend Arun recently shifted to a smaller apartment to cut down his monthly rent, which had gone up to twenty-two thousand rupees. His new place costs fourteen thousand a month and is only three kilometres from his office.",questions=["Why did Arun shift to a smaller apartment?","How much is his new rent?"],key_facts=[["rent","high rent"],["fourteen thousand","14,000"]]),
    ListeningClip("q22","QnA","The cooking competition at the cultural festival had thirty-five participants from across the state. The winner, a homemaker from Trichy, prepared a three-course traditional meal in under forty-five minutes and won a cash prize of fifty thousand rupees.",questions=["How many people participated in the cooking competition?","What did the winner receive?"],key_facts=[["thirty-five","35"],["fifty thousand","50,000"]]),
    ListeningClip("q23","QnA","The technology park near the airport has started offering affordable co-working spaces for freelancers and start-ups. Memberships start from two thousand rupees a month and include high-speed internet, printing facilities, and a pantry.",questions=["Who is the co-working space meant for?","What is the starting price of a membership?"],key_facts=[["freelancers","start-ups"],["two thousand","2000"]]),
    ListeningClip("q24","QnA","The annual trade fair at the exhibition grounds will be held from the tenth to the seventeenth of this month. Stall bookings are open online and the entry fee for visitors is fifty rupees per head. Children below ten enter free.",questions=["On which dates is the trade fair held?","What is the entry fee for visitors?"],key_facts=[["tenth","seventeenth"],["fifty","50"]]),
    ListeningClip("q25","QnA","The farmers in the village have formed a cooperative society to sell their produce directly to consumers, cutting out middlemen. They now conduct a weekly market every Saturday near the panchayat office and have seen their earnings rise by nearly thirty percent.",questions=["What is the purpose of the cooperative society?","How much have the farmers' earnings increased?"],key_facts=[["sell directly","remove middlemen","direct to consumers"],["thirty percent","30"]]),
    ListeningClip("q26","QnA","The neighbourhood watch group meets every second and fourth Saturday evening at the park entrance to discuss safety concerns and coordinate with the local police station. The group has eighty-three registered members.",questions=["When does the neighbourhood watch group meet?","How many members does the group have?"],key_facts=[["second","fourth Saturday"],["eighty-three","83"]]),
    ListeningClip("q27","QnA","The new recycling initiative at the office asks employees to sort their waste into three categories — paper, plastic, and organic. Collection bins have been placed on every floor and a recycling agency picks up the sorted waste every Wednesday.",questions=["How many waste categories must employees sort into?","When is the waste collected by the recycling agency?"],key_facts=[["three","3"],["Wednesday"]]),
    ListeningClip("q28","QnA","The college library has recently added a digital reading section with twenty tablet devices loaded with e-books and journals. Students can use the tablets for a maximum of two hours per session and must book a slot at the front desk.",questions=["How many tablet devices are available in the digital reading section?","For how long can a student use a tablet per session?"],key_facts=[["twenty","20"],["two hours"]]),
    ListeningClip("q29","QnA","Santhosh left his stable bank job to become a wildlife photographer after spending years on the side. He recently returned from a six-week expedition in the Western Ghats and his photographs were featured in a national geography magazine.",questions=["What did Santhosh do before becoming a wildlife photographer?","How long was his expedition in the Western Ghats?"],key_facts=[["bank job","banker"],["six weeks","six-week"]]),
    ListeningClip("q30","QnA","The new traffic signal timing system introduced at five major junctions in the city uses sensor data to adjust green light duration based on live traffic flow. The pilot project will run for three months before a city-wide rollout.",questions=["What technology does the new traffic signal system use?","How long will the pilot project run?"],key_facts=[["sensor","sensor data"],["three months"]]),
    ListeningClip("q31","QnA","A local NGO has launched a programme to teach digital literacy to women above the age of fifty in rural areas. The classes are held three times a week at the village community hall and are completely free of charge.",questions=["Who is the digital literacy programme targeted at?","How often are the classes held?"],key_facts=[["women","above fifty","rural"],["three times a week"]]),
    ListeningClip("q32","QnA","The concert organised by the music school will be held at the open-air amphitheatre on the last Sunday of this month starting at six thirty in the evening. Entry is by invitation only, and tickets were distributed to students and their families last week.",questions=["Where will the concert be held?","Who received the tickets?"],key_facts=[["amphitheatre"],["students","families"]]),
    ListeningClip("q33","QnA","The water tanker that supplies drinking water to three colonies in the ward has been out of service for the past four days due to a pump failure. The corporation has arranged a temporary supply through private tankers until the vehicle is repaired.",questions=["Why has the water tanker been out of service?","What temporary arrangement has been made?"],key_facts=[["pump failure"],["private tankers"]]),
    ListeningClip("q34","QnA","Nithya has been shortlisted for a six-month fellowship programme at a research institute in Bengaluru. The fellowship covers accommodation, a monthly stipend of twenty-five thousand rupees, and access to the institute's laboratories.",questions=["Where is the fellowship programme located?","What does the fellowship include?"],key_facts=[["Bengaluru"],["accommodation","stipend","twenty-five thousand","laboratory"]]),
    ListeningClip("q35","QnA","A newly opened children's science museum in the city has interactive exhibits on topics such as space, the human body, and climate change. School groups can book guided tours on weekdays at a discounted group rate of forty rupees per student.",questions=["What topics do the museum's exhibits cover?","What is the group rate for school students?"],key_facts=[["space","human body","climate"],["forty","40"]]),
    ListeningClip("q36","QnA","The landlord of the commercial building has given tenants two weeks' notice to vacate the ground-floor shops due to renovation work. A few shopkeepers have been temporarily relocated to the adjacent lane.",questions=["Why have the ground-floor shopkeepers been asked to vacate?","Where have some shopkeepers been relocated?"],key_facts=[["renovation"],["adjacent lane"]]),
    ListeningClip("q37","QnA","The department store is running a clearance sale on winter clothing with discounts of up to sixty percent. The sale started on Monday and will continue until stocks last, with new items added every morning at nine.",questions=["What is the maximum discount offered in the clearance sale?","When does the store add new items?"],key_facts=[["sixty percent","60"],["nine","every morning"]]),
    ListeningClip("q38","QnA","Arjun had been practising for the state-level chess championship for nearly a year. He finally participated last month and reached the quarter-finals before losing to a former national champion. His coach says he will be ready for the nationals next year.",questions=["How long had Arjun been practising for the championship?","How far did he reach in the competition?"],key_facts=[["nearly a year","one year"],["quarter-finals","quarterfinals"]]),
    ListeningClip("q39","QnA","The school has introduced a five-day outdoor education camp for students in Grade Nine as part of the curriculum. The camp will be held at a nature reserve sixty kilometres from the city and will cover survival skills, teamwork, and wildlife awareness.",questions=["For which grade is the outdoor education camp?","Where will the camp be held?"],key_facts=[["Grade Nine","Grade 9"],["nature reserve","sixty kilometres"]]),
    ListeningClip("q40","QnA","A power cut lasting nearly four hours affected several parts of the western zone of the city yesterday evening. The electricity board confirmed that a high-tension wire had snapped near the sub-station and repairs were completed by midnight.",questions=["How long did the power cut last?","What caused the power cut?"],key_facts=[["four hours"],["high-tension wire","snapped","wire"]]),
    ListeningClip("q41","QnA","The new public library in the town square has a collection of over forty thousand books in six languages and also offers a children's section with illustrated story books and audio books. Membership is free for school and college students.",questions=["How many books does the library have?","Who gets free membership?"],key_facts=[["forty thousand","40,000"],["school","college students"]]),
    ListeningClip("q42","QnA","The company has decided to sponsor ten employees to pursue a part-time MBA programme at a recognised business school. Selected employees will have their tuition fees fully reimbursed and will be given flexible working hours on class days.",questions=["How many employees will be sponsored for the MBA?","What support will selected employees receive?"],key_facts=[["ten","10"],["tuition fees","flexible hours"]]),
    ListeningClip("q43","QnA","The heavy rain last Tuesday caused waterlogging on the main road outside the station, forcing commuters to wade through knee-deep water for nearly two hours. The drainage department cleared the blockage by early evening.",questions=["What caused the waterlogging on the main road?","How long did commuters face difficulty?"],key_facts=[["heavy rain","rainfall"],["two hours","nearly two hours"]]),
    ListeningClip("q44","QnA","The regional cooking festival held last weekend showcased dishes from twelve different states. Over three thousand visitors attended, and the stall representing Kerala won the best presentation award for the second year in a row.",questions=["How many states were represented at the cooking festival?","Which stall won the best presentation award?"],key_facts=[["twelve","12"],["Kerala"]]),
    ListeningClip("q45","QnA","The state government has announced free coaching for students from government schools who are preparing for engineering and medical entrance exams. The classes will be held on weekends at district headquarters and are open to students in Classes Eleven and Twelve.",questions=["For which exams is free coaching being offered?","When will the classes be held?"],key_facts=[["engineering","medical entrance"],["weekends","Saturday","Sunday"]]),
    ListeningClip("q46","QnA","An old building near the city centre that had been vacant for over twenty years is being converted into a heritage hotel. The renovation is expected to cost three crore rupees and the hotel is planned to open by the end of next year.",questions=["What is the old building being converted into?","What is the expected cost of renovation?"],key_facts=[["heritage hotel"],["three crore"]]),
    ListeningClip("q47","QnA","The office has implemented a new rule that all meetings must start and end on time, and no meeting should be scheduled for more than forty-five minutes without prior approval from the department head. The rule applies from this Monday.",questions=["What is the new rule regarding meetings?","From when does the rule apply?"],key_facts=[["forty-five minutes","45 minutes","on time"],["this Monday","Monday"]]),
    ListeningClip("q48","QnA","A talented young artist from our city has won an international painting competition held in Paris, becoming the youngest Indian winner in the event's thirty-year history. She created a large canvas depicting the fishing community along the coast.",questions=["Where was the international painting competition held?","What was the subject of the winning painting?"],key_facts=[["Paris"],["fishing community","coast","fishermen"]]),
    ListeningClip("q49","QnA","The new organic food store that opened last month near the university sources all its products directly from certified farms within a hundred kilometres of the city. It currently stocks over two hundred items and offers home delivery within four hours.",questions=["From where does the store source its products?","How quickly does it offer home delivery?"],key_facts=[["certified farms","hundred kilometres"],["four hours"]]),
    ListeningClip("q50","QnA","The city marathon is scheduled for the second Sunday of next month and registrations are open on the official website until the end of this week. Participants can choose from three categories — five kilometres, ten kilometres, or the full forty-two kilometre race.",questions=["By when should participants register for the marathon?","What distance categories are available?"],key_facts=[["end of this week"],["five kilometres","ten kilometres","forty-two","5","10","42"]]),
]


# ─────────────────────────────────────────────────────────────────────────────
# Session selector — called once per test session
# ─────────────────────────────────────────────────────────────────────────────

def get_session_clips(seed: int = None) -> list[ListeningClip]:
    """
    Pick 2 REPEAT + 2 QnA clips randomly for this session.
    Returns them as clip_1..clip_4 (sequential IDs for the session).
    Each call gives a different combination without repetition.
    """
    rng = random.Random(seed)
    picks = rng.sample(REPEAT_CLIPS, 2) + rng.sample(QNA_CLIPS, 2)

    session = []
    for i, clip in enumerate(picks, start=1):
        c = deepcopy(clip)
        c.clip_id = f"clip_{i}"
        session.append(c)

    return session